version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Pakai Dockerfile khusus dev
    volumes:
      - .:/app  # Sinkronisasi kode host <-> container
      - /app/bin  # Ignore bin supaya tidak overwrite di container
    ports:
      - "8080:8080"
    networks:
      - dev_network
    depends_on:
      - db
    command: ["air"]

  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_app_dev
      MYSQL_USER: yurina
      MYSQL_PASSWORD: hirate
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - dev_network
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 20s
      retries: 10

volumes:
  db_data:

networks:
  dev_network:
    driver: bridge