version: "3.9"

services:
  app:
    container_name: go_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my_network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=yurina
      - DB_PASSWORD=hirate
      - DB_NAME=go_app
    volumes:
      - ./config:/app/config
    command: ["/app/wait-for.sh", "db:3306", "--", "/app/start.sh"]

  db:
    container_name: mysql_db
    image: mysql:8.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_app
      MYSQL_USER: yurina
      MYSQL_PASSWORD: hirate
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  my_network:

volumes:
  mysql_data: