version: '3.8'

services:
  app:
    build: .
    container_name: go-template
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=yurina
      - DB_PASSWORD=hirate
      - DB_NAME=gotemplate
      - DB_PORT=3306
    volumes:
      - .:/app

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: hirate
      - MYSQL_DATABASE: gotemplate
    volumes:
      - mysql_data :/var/lib/mysql

volumes:
  mysql_data: