# Gunakan official Go image
FROM golang:1.24.1 AS dev

WORKDIR /app

# Install air (hot reload)
RUN go install github.com/air-verse/air@latest

# Copy go.mod dan go.sum lebih dulu untuk caching
COPY go.mod go.sum ./
RUN go mod download

# Copy seluruh kode ke dalam container
COPY . .

# Expose port aplikasi
EXPOSE 8080

CMD ["air"]