log:
  level: "info"      # Level log: debug, info, warn, error
  files:  # Lokasi penyimpanan log
      info : "logs/info.log"
      error : "logs/error.log"
  max_size: 10       # Maksimal ukuran file log (MB)
  max_backups: 5     # Jumlah maksimum backup file log
  max_age: 30        # Lama penyimpanan file log (hari)
  compress: true     # Kompres file log lama (gzip)

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"
  name: "mydb"
  max_open_cons: 10
  max_idle_cons: 5
  max_life_time : 5 #time * minutes

server:
  port: 8080